dataset_path: ohjoonhee/frozenlake_vqa
dataset_kwargs:
  token: True
task: "frozenlake"
test_split: test
output_type: generate_until
doc_to_visual: !function utils.frozenlake_doc_to_visual
doc_to_text: !function utils.frozenlake_doc_to_text
doc_to_target: "answer"
generation_kwargs:
  max_new_tokens: 4096
  temperature: 0
  do_sample: False
process_results: !function utils.frozenlake_process_results
metric_list:
  - metric: parsed_match
    aggregation: mean
    higher_is_better: true
  # - metric: llm_match
  #   aggregation: mean
  #   higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""
metadata:
  - version: 0.0
