dataset_path: ohjoonhee/mazenav_vqa
dataset_kwargs:
  token: True
task: "mazenav_vqa"
test_split: test
output_type: generate_until
doc_to_visual: !function utils.mazenav_doc_to_visual
doc_to_text: !function utils.mazenav_doc_to_text
doc_to_target: "answer"
generation_kwargs:
  max_new_tokens: 1024
  temperature: 0.2
  do_sample: True
  num_beams: 1
process_results: !function utils.mazenav_process_results
metric_list:
  - metric: parsed_match
    aggregation: mean
    higher_is_better: true
  # - metric: llm_match
  #   aggregation: mean
  #   higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""
metadata:
  - version: 0.0
