dataset_path: MilaWang/SpatialEval
dataset_name: vqa
dataset_kwargs:
  token: True
task: "mazenav"
test_split: test
process_docs: !function utils.mazenav_process_docs
output_type: generate_until
doc_to_visual: !function utils.mazenav_doc_to_visual
doc_to_text: !function utils.mazenav_doc_to_text
doc_to_target: "oracle_answer"
generation_kwargs:
  max_new_tokens: 32
  temperature: 0
  do_sample: False
process_results: !function utils.mazenav_process_results
metric_list:
  - metric: parsed_match
    aggregation: mean
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""
  qwen_vl:
    pre_prompt: ""
    post_prompt: ""
metadata:
  - version: 0.0
